version: '3'
services:
  backoffice:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./apps/backoffice/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        - NEXTAUTH_URL=$NEXTAUTH_URL
        - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
        - NEXT_PUBLIC_NODE_ENV=$NEXT_PUBLIC_NODE_ENV
    ports:
    - '3002:3002'
